name: beenotes
description: Bee Notes.

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.0.0+3
  path_provider: ^2.0.2
  intl: 0.17.0
  flutter_staggered_grid_view: 0.4.0
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_small.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans_Regular.ttf
        - asset: assets/fonts/ProductSans_Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans_Bold.ttf
          weight: 700
