/// Generated by AssetsRefGenerator on 2021/08/16
class Res {
  static const String logo = "assets/logo.png";
  static const String ProductSans_Bold = "assets/fonts/ProductSans_Bold.ttf";
  static const String ProductSans_Italic = "assets/fonts/ProductSans_Italic.ttf";
  static const String ProductSans_Regular = "assets/fonts/ProductSans_Regular.ttf";
}
